{
 "title": "Executive Sales Overview",
 "time": { "from": "2025-03-16T04:00:00.000Z", "to": "2025-03-18T03:59:59.000Z" },
 "panels": [
  {
   "title": "Overall Return Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    SUM(CASE WHEN is_return = TRUE THEN 1 ELSE 0 END) AS total_returns,\r\n    COUNT(*) AS total_transactions,\r\n    (SUM(CASE WHEN is_return = TRUE THEN 1 ELSE 0 END) * 100.0 / COUNT(*)) AS return_percentage\r\nFROM \"GFRetail\".transactions;"
    }
   ]
  },
  {
   "title": " Sales Performance by Store",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    s.store_name,\r\n    SUM(t.line_total) AS total_sales\r\nFROM \"GFRetail\".transactions t\r\nJOIN \"GFRetail\".stores s ON t.store_id = s.store_id\r\nGROUP BY s.store_name\r\nORDER BY total_sales DESC;"
    }
   ]
  },
  {
   "title": "Top Selling Products",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    p.description_en AS product_name,\r\n    SUM(t.quantity) AS total_quantity_sold,\r\n    SUM(t.line_total) AS total_revenue\r\nFROM \"GFRetail\".transactions t\r\nJOIN \"GFRetail\".products p ON t.product_id = p.product_id\r\nGROUP BY p.description_en\r\nORDER BY total_quantity_sold DESC\r\nLIMIT 10; -- Show top 10"
    }
   ]
  },
  {
   "title": "Daily Store Sales",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  sale_date AS time,\r\n  store_id,\r\n  total_sales\r\nFROM \"GFRetail\".daily_store_sales\r\nWHERE $__timeFilter(sale_date)\r\nORDER BY sale_date;"
    }
   ]
  },
  {
   "title": "Product Performance by Category",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    p.category,\r\n    SUM(t.line_total) AS total_revenue\r\nFROM \"GFRetail\".transactions t\r\nJOIN \"GFRetail\".products p ON t.product_id = p.product_id\r\nGROUP BY p.category\r\nORDER BY total_revenue DESC;"
    }
   ]
  },
  {
   "title": "Employee Performance (Sales)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    e.name AS employee_name,\r\n    SUM(t.line_total) AS total_sales\r\nFROM \"GFRetail\".transactions t\r\nJOIN \"GFRetail\".employees e ON t.employee_id = e.employee_id\r\nGROUP BY e.name\r\nORDER BY total_sales DESC;"
    }
   ]
  }
 ]
}